### PR TITLE
Option to add custom text or General Terms on new page

### PR DESCRIPTION
**Pull request by dragonfly4**
With this option you can add your general terms of each invoice. It will be added to a new page without the header. I use a 2 column layout as it is multi-language, but you can also use the full width.

### CODE REVIEW

**Comment by fulopattila122** [comment]
Same here, please resolve the merge conflict. Thanks!

**Comment by dragonfly4** [comment]
@fulopattila122 this option has also been integrated on my side based on the latest release. Are you interested to add this? Then I'll create a PR if #62 is accepted.

**Comment by fulopattila122** [comment]
@dragonfly4 Yes, please submit the PR. #62 has been merged. Thanks for that as well :wink: 

I'll create the next release so that it'll contain #62 and your new PR.

**Comment by dragonfly4** [comment]
@fulopattila122 You are welcome! And done for the extra pages
https://github.com/artkonekt/pdf-invoice/pull/64

**Pull request closed without merging**
