### PR TITLE
Remove empty line when Item text is empty

### PR DESCRIPTION
**Pull request by dragonfly4**

### CODE REVIEW

**Comment by dragonfly4** [comment]
Currently

ItemEmpty01

After the fix

ItemEmpty02

**Comment by fulopattila122** [comment]
@dragonfly4 I'd like to merge this PR, but it conflicts with the master branch. Could you please resolve it? Then I'll merge it a make a new release.
Cheers

**Comment by dragonfly4** [comment]
@fulopattila122 Too many changes in separate PR's gives issues. Re-forked so please try again. I'll check #26 when this one is closed.

**Comment by fulopattila122** [comment]
Hi, I'd be happy to merge, but still conflicting. If you fix it I'll merge and release it. Thx!

**Comment by dragonfly4** [comment]
@fulopattila122 I'll wait for https://github.com/artkonekt/pdf-invoice/pull/31 and then do a PR from the latest release.

**Comment by fulopattila122** [comment]
@dragonfly4 #31 has been merged, could you please resolve the merge conflicts, I'm about to create a new release and would be nice to include this as well. thx!

**Comment by dragonfly4** [comment]
> @dragonfly4 #31 has been merged, could you please resolve the merge conflicts, I'm about to create a new release and would be nice to include this as well. thx!

This week no time but I'll have a look next week.

**Comment by dragonfly4** [comment]
@fulopattila122 Apologies for the long delay. I have created a new Pull Request for this based on the latest release.

https://github.com/artkonekt/pdf-invoice/pull/62

**Pull request closed without merging**
