### PR TITLE
[FEATURE] Allow to override alignment of paragraphs

### PR DESCRIPTION
**Pull request by mickaelperrin**
Hi,

Not sure if this will interest you.

This is a little patch that allows overriding the alignment of text paragraphs, mainly to use justify.

### CODE REVIEW

**Comment by fulopattila122** [comment]
Hi Mickael,

Could you please also extend addParagraph occurrences in README with this parameter?
I only would merge this nice PR with the doc also in sync with what the code does.

Thx

**Comment by mickaelperrin** [comment]
Yeah, I understand, that's a nice policy.

I think I will work on this next week. I need to do some more tests because I have an issue with that on a production website that uses my forked library. I need to investigate to see if this is something related to this PR or not.

**Comment by fulopattila122** [comment]
Cool! Just ping this PR whenever you think it's ready.

**Comment by fulopattila122** [comment]
I close this since there was no activity for about 4 years

**Pull request closed without merging**
